<a href="https://colab.research.google.com/github/Alex-Ukraine/python-intermediate/blob/master/random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
import random

In [116]:
mylist = list("ABCDEFGH")
a = random.sample(mylist, 3)
print(a)

['F', 'G', 'H']


In [117]:
mylist = list("ABCDEFGH")
a = random.choices(mylist, k=3)
print(a)

['E', 'G', 'D']


In [118]:
import secrets

In [119]:
a = secrets.randbelow(10)
print(a)

1


In [120]:
a = secrets.randbits(3)
print(a)

1


In [121]:
mylist = list("ABCDEFGH")
a = secrets.choice(mylist)
print(a)

C


In [122]:
import numpy as np

In [123]:
a = np.random.rand(10, 3)
print(a)

[[0.4229748  0.08707189 0.1970822 ]
 [0.51587734 0.5058081  0.7409749 ]
 [0.63026148 0.75303417 0.99118965]
 [0.18350636 0.33405176 0.63623015]
 [0.98056381 0.45175518 0.25801462]
 [0.13544568 0.0559054  0.23389256]
 [0.85461123 0.34006986 0.82719142]
 [0.14399528 0.55046773 0.80670432]
 [0.53888025 0.96834176 0.11529689]
 [0.44355894 0.26949136 0.52910671]]


In [124]:
a = np.random.randint(0, 10, 3)
print(a)

[2 0 9]


In [125]:
a = np.random.randint(0, 10, (3, 4))
print(a)

[[5 6 6 9]
 [9 3 5 6]
 [0 4 0 6]]
